### ISSUE TITLE
Color/Shape decorator proposal

### ISSUE THREAD

**Issue by lazarljubenovic** [lazarljubenovic/grafaro#4]
# Cilj

Konciznan API za fleksibilno, centralizovano i predvidivo dodeljivanje pravila za bojenje čvorova stanja algoritma.

# Predlog

Dekorator primenjujemo nad čitavom `State` klasom (konkretna impl klase `AlgorithmState`). Parametar dekoratora je objekat sa propertijima `nodes` i `edges`. Oba su **nizovi** koji primaju funkcije sa sledećim potpisima, respektivno.

    (state: State, nodeLabel: string) => GrfColor | null
    (state: State, edgeLabel: string) => GrfColor | null

Prilikom normalizacije stanja, zovemo ove funkcije redom kojim su zadati. Ako funkcija vrati tip `number` (po statičkom tipu iz TS-a znamo da se radi o enumeraciji za boju), uzimamo tu boju za čvor i pretraga se prekida. Ako se vrati tip `object`, to je `null` (jer JavaScript -- vidi sliku :point_down:). U tom slučaju se pretraga nastavlja dalje niz niz :trumpet:. Ako se dođe do kraja niza, a povratana vrednost je ponovo bila `null`, zove se funkcija za pribavljanje podrazumevane boje (koja će biti promenjena da vraća **uvek** `GrfColor.DEFAULT`, a ne da se oslanja na postojanje `currentNode` u izvedenim klasama).

![image](https://cloud.githubusercontent.com/assets/7661457/22842884/4022d1e4-efd7-11e6-9e5a-009a62458123.png)

Ovako imamo definisane prioritete. Na primer, u našim implementacijama skoro uvek hoćemo da pre svega obojimo `currentNode`, gde god se on drugde našao u nizu.

    (state: State, nodeLabel: string) => state.currentNode == nodeLabel ? Grfolor.ACCENT : null

Ako hoćemo da sve susede obojimo `SECONDARY`, a da trenutni sused bude `PRIMARY`, redom dajedmo sledeće funkcije:

    (state: State, nodeLabel: string) => state.

# Posledice

- Izvedene klase samo u dekoratorima definišu pravila za bojenje.
- Ova pravila se koriste za generisanje boja i za graf i za debag-tejbl i sakrivena su od konkretnih algoritama.
- Obrati pažnju da sem toga što smo ispoštovali zahtev "jedan čvor uvek oboji u istu boju" o kome smo pričali danas, nemamo više ni onu groznu sintaksu sa stringovima kao stvarnim parametrima, jer jednostavno uzimamo celo stanje. Mada je ovo moglo i ranije, tada nije imalo smisla semantički jer smo se vezivali za konkretan properti klase. Sada je ovo svakako dekorator klase tako da imati objekat klase kao parameter skroz ima smisla.
- _Trebalo_ bi da je prilično jednostavno za implementaciju, bez kupusa kog sa stringovima kao imenima.

# Alternative

Niz bi mogao i da se posmatra ne kao niz prioriteta nego kao niz "prebojavanja". Vraćanje `null` onda jednostavno ne bi diralo prethodnu boju, a sledeća boja koja dođe bi preklopila staru. Oba imaju smisla.
  - Prvi način je logičan jer se odmah pišu najbitnije stvari i odmah se izdvajaju celine koje znamo da će da budu takve (ništa _posle_ ne može da naruši ono što smo dosada pročitali, dok gledamo kod -- generlano dobra praksa da nema "lookahead"-a u logici).
  - Drugi način je logičan jer se model inkerementalno izgrađuje element po element iz niza: prvo obojimo sve susede jer su svi oni susedi, a _onda_ posebno naznačimo trenutni.

Ako nema nikakvih posebnih prednosti za drugi, biramo prvi zbog perfa (kod drugog uvek moramo da odemo do kraja niza).

**Comment by Pritilender** [comment]
Može. Deluje normalnije i bolje nego što je trenutno svakako. A i mislim da ćemo dobiti možda čak i fin interfejs da mogu korisnici ili ko već da prošire bojenje nekom novom paletom.
